
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async validateBoard(board: string) : Promise<Result<CardDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_board", { board }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateConfig(config: GameConfigDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSolve(config: SolveConfig) : Promise<Result<TreeInfoDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_solve", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSolve() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_solve") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSolveStatus() : Promise<Result<SolveProgressDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_solve_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStrategyMatrix(nodeId: number) : Promise<Result<StrategyMatrixDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_strategy_matrix", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHandDetail(nodeId: number, handIdx: number) : Promise<Result<HandDetailDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hand_detail", { nodeId, handIdx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNodeEv(nodeId: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_node_ev", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTreeStructure() : Promise<Result<TreeNodeDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tree_structure") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNode(nodeId: number) : Promise<Result<TreeNodeDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_node", { nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
solveComplete: SolveComplete,
solveProgress: SolveProgress
}>({
solveComplete: "solve-complete",
solveProgress: "solve-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type ActionDto = { label: string; action_type: string; size: number | null }
export type CardDto = { value: number; rank: string; suit: string; display: string }
export type GameConfigDto = { board: string; pot: number; stacks: number; bet_sizes: number[]; raise_sizes: number[]; max_raises_per_street: number; allin_threshold: number }
export type HandDetailDto = { hand: string; cards: [CardDto, CardDto]; frequencies: number[]; ev: number; equity: number | null }
export type MatrixCellDto = { hand_label: string; row: number; col: number; is_pair: boolean; is_suited: boolean; frequencies: number[]; ev: number | null; combos: number }
export type MemoryReportDto = { tree_mb: number; storage_mb: number; rank_cache_mb: number; conflict_table_mb: number; total_mb: number }
export type SolveComplete = SolveProgressDto
export type SolveConfig = { game: GameConfigDto; max_iterations: number; threshold: number; check_every: number; time_cap_secs: number }
export type SolveProgress = SolveProgressDto
export type SolveProgressDto = { iteration: number; max_iterations: number; exploitability: number; ip_br: number; oop_br: number; elapsed_secs: number; status: SolveStatus }
export type SolveStatus = "Idle" | "Building" | "Solving" | "Converged" | "Stopped" | { Error: { message: string } }
export type StrategyMatrixDto = { node_id: number; player: string; actions: ActionDto[]; cells: MatrixCellDto[] }
export type TreeInfoDto = { total_nodes: number; decision_nodes: number; chance_nodes: number; terminal_nodes: number; num_hands: number; memory: MemoryReportDto }
export type TreeNodeDto = { id: number; node_type: string; player: string | null; street: string | null; actions: ActionDto[]; children: number[]; pot: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
